In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option('display.max_columns', None)
df = pd.read_csv("DrDoS_DNS.csv")

df.columns = df.columns.str.strip()

df.head()

C:\Users\evanm\AppData\Local\Temp\ipykernel_32908\3568587498.py:7: DtypeWarning: Columns (85) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("DrDoS_DNS.csv")

,Unnamed: 0,Flow ID,Source IP,Source Port,Destination IP,Destination Port,Protocol,Timestamp,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,Bwd Packet Length Max,Bwd Packet Length Min,Bwd Packet Length Mean,Bwd Packet Length Std,Flow Bytes/s,Flow Packets/s,Flow IAT Mean,Flow IAT Std,Flow IAT Max,Flow IAT Min,Fwd IAT Total,Fwd IAT Mean,Fwd IAT Std,Fwd IAT Max,Fwd IAT Min,Bwd IAT Total,Bwd IAT Mean,Bwd IAT Std,Bwd IAT Max,Bwd IAT Min,Fwd PSH Flags,Bwd PSH Flags,Fwd URG Flags,Bwd URG Flags,Fwd Header Length,Bwd Header Length,Fwd Packets/s,Bwd Packets/s,Min Packet Length,Max Packet Length,Packet Length Mean,Packet Length Std,Packet Length Variance,FIN Flag Count,SYN Flag Count,RST Flag Count,PSH Flag Count,ACK Flag Count,URG Flag Count,CWE Flag Count,ECE Flag Count,Down/Up Ratio,Average Packet Size,Avg Fwd Segment Size,Avg Bwd Segment Size,Fwd Header Length.1,Fwd Avg Bytes/Bulk,Fwd Avg Packets/Bulk,Fwd Avg Bulk Rate,Bwd Avg Bytes/Bulk,Bwd Avg Packets/Bulk,Bwd Avg Bulk Rate,Subflow Fwd Packets,Subflow Fwd Bytes,Subflow Bwd Packets,Subflow Bwd Bytes,Init_Win_bytes_forward,Init_Win_bytes_backward,act_data_pkt_fwd,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,SimillarHTTP,Inbound,Label
0,425,172.16.0.5-192.168.50.1-634-60495-17,172.16.0.5,634,192.168.50.1,60495,17,2018-12-01 10:51:39.813448,28415,97,0,42680.0,0.0,440.0,440.0,440.0,0.0,0.0,0.0,0.0,0.0,1.502024e+06,3413.689952,295.989583,500.959301,3596.0,1.0,28415.0,295.989583,500.959301,3596.0,1.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,-97,0,3413.689952,0.0,440.0,440.0,440.0,0.0,0.0,0,0,0,0,0,0,0,0,0.0,444.536082,440.0,0.0,-97,0,0,0,0,0,0,97,42680,0,0,-1,-1,96,-1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,DrDoS_DNS
1,430,172.16.0.5-192.168.50.1-60495-634-17,192.168.50.1,634,172.16.0.5,60495,17,2018-12-01 10:51:39.820842,2,2,0,880.0,0.0,440.0,440.0,440.0,0.0,0.0,0.0,0.0,0.0,4.400000e+08,1000000.000000,2.000000,0.000000,2.0,2.0,2.0,2.000000,0.000000,2.0,2.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,-2,0,1000000.000000,0.0,440.0,440.0,440.0,0.0,0.0,0,0,0,0,0,0,0,0,0.0,660.000000,440.0,0.0,-2,0,0,0,0,0,0,2,880,0,0,-1,-1,1,-1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,DrDoS_DNS
2,1654,172.16.0.5-192.168.50.1-634-46391-17,172.16.0.5,634,192.168.50.1,46391,17,2018-12-01 10:51:39.852499,48549,200,0,88000.0,0.0,440.0,440.0,440.0,0.0,0.0,0.0,0.0,0.0,1.812602e+06,4119.549321,243.964824,578.101371,5418.0,1.0,48549.0,243.964824,578.101371,5418.0,1.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,-200,0,4119.549321,0.0,440.0,440.0,440.0,0.0,0.0,0,0,0,0,0,0,0,0,0.0,442.200000,440.0,0.0,-200,0,0,0,0,0,0,200,88000,0,0,-1,-1,199,-1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,DrDoS_DNS
3,2927,172.16.0.5-192.168.50.1-634-11894-17,172.16.0.5,634,192.168.50.1,11894,17,2018-12-01 10:51:39.890213,48337,200,0,88000.0,0.0,440.0,440.0,440.0,0.0,0.0,0.0,0.0,0.0,1.820552e+06,4137.617146,242.899497,485.292695,3337.0,1.0,48337.0,242.899497,485.292695,3337.0,1.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,-200,0,4137.617146,0.0,440.0,440.0,440.0,0.0,0.0,0,0,0,0,0,0,0,0,0.0,442.200000,440.0,0.0,-200,0,0,0,0,0,0,200,88000,0,0,-1,-1,199,-1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,DrDoS_DNS
4,694,172.16.0.5-192.168.50.1-634-27878-17,172.16.0.5,634,192.168.50.1,27878,17,2018-12-01 10:51:39.941151,32026,200,0,88000.0,0.0,440.0,440.0,440.0,0.0,0.0,0.0,0.0,0.0,2.747767e+06,6244.925998,160.934673,196.891271,1236.0,0.0,32026.0,160.934673,196.891271,1236.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,-200,0,6244.925998,0.0,440.0,440.0,440.0,0.0,0.0,0,0,0,0,0,0,0,0,0.0,442.200000,440.0,0.0,-200,0,0,0,0,0,0,200,88000,0,0,-1,-1,199,-1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,DrDoS_DNS

In [3]:
print(df.shape)          # how many rows and columns
print(df.dtypes)         # column types


print(df['Label'].value_counts())  # how many normal vs attack rows

(5074413, 88)
Unnamed: 0          int64
Flow ID            object
Source IP          object
Source Port         int64
Destination IP     object
                   ...
Idle Max          float64
Idle Min          float64
SimillarHTTP       object
Inbound             int64
Label              object
Length: 88, dtype: object
Label
DrDoS_DNS    5071011
BENIGN          3402
Name: count, dtype: int64

In [4]:
print(df.isnull().sum())
print(df.describe())

Unnamed: 0        0
Flow ID           0
Source IP         0
Source Port       0
Destination IP    0
                 ..
Idle Max          0
Idle Min          0
SimillarHTTP      0
Inbound           0
Label             0
Length: 88, dtype: int64
         Unnamed: 0   Source Port  Destination Port      Protocol  \
count  5.074413e+06  5.074413e+06      5.074413e+06  5.074413e+06
mean   1.380064e+04  8.000962e+02      3.279212e+04  1.699142e+01
std    8.020386e+03  1.851189e+03      1.892478e+04  3.194000e-01
min    0.000000e+00  0.000000e+00      0.000000e+00  0.000000e+00
25%    6.844000e+03  5.810000e+02      1.643000e+04  1.700000e+01
50%    1.377600e+04  7.270000e+02      3.279400e+04  1.700000e+01
75%    2.074100e+04  8.750000e+02      4.918300e+04  1.700000e+01
max    2.818200e+04  6.550800e+04      6.553500e+04  1.700000e+01

       Flow Duration  Total Fwd Packets  Total Backward Packets  \
count   5.074413e+06       5.074413e+06            5.074413e+06
mean    7.176140e+03       6.013596e+00            8.004867e-03
std     7.711845e+05       5.953501e+02            2.950822e+00
min     0.000000e+00       1.000000e+00            0.000000e+00
25%     1.000000e+00       2.000000e+00            0.000000e+00
50%     1.000000e+00       2.000000e+00            0.000000e+00
75%     2.000000e+00       2.000000e+00            0.000000e+00
max     1.200000e+08       1.001480e+05            4.602000e+03

       Total Length of Fwd Packets  Total Length of Bwd Packets  \
count                 5.074413e+06                 5.074413e+06
mean                  2.952438e+03                 6.768139e+00
std                   9.122037e+03                 6.837585e+03
min                   0.000000e+00                 0.000000e+00
25%                   2.928000e+03                 0.000000e+00
50%                   2.944000e+03                 0.000000e+00
75%                   2.944000e+03                 0.000000e+00
max                   1.526642e+07                 1.099376e+07

       Fwd Packet Length Max  Fwd Packet Length Min  Fwd Packet Length Mean  \
count           5.074413e+06           5.074413e+06            5.074413e+06
mean            1.377942e+03           1.377609e+03            1.377831e+03
std             2.999557e+02           3.004828e+02            2.996888e+02
min             0.000000e+00           0.000000e+00            0.000000e+00
25%             1.464000e+03           1.464000e+03            1.464000e+03
50%             1.472000e+03           1.472000e+03            1.472000e+03
75%             1.472000e+03           1.472000e+03            1.472000e+03
max             3.212000e+04           2.020000e+03            3.015291e+03

       Fwd Packet Length Std  Bwd Packet Length Max  Bwd Packet Length Min  \
count           5.074413e+06           5.074413e+06           5.074413e+06
mean            7.593553e-02           2.484989e-01           2.243609e-02
std             5.349133e+00           2.987653e+01           1.735238e+00
min             0.000000e+00           0.000000e+00           0.000000e+00
25%             0.000000e+00           0.000000e+00           0.000000e+00
50%             0.000000e+00           0.000000e+00           0.000000e+00
75%             0.000000e+00           0.000000e+00           0.000000e+00
max             2.221556e+03           3.358000e+04           1.072000e+03

       Bwd Packet Length Mean  Bwd Packet Length Std  Flow Bytes/s  \
count            5.074413e+06           5.074413e+06  5.074382e+06
mean             7.309350e-02           7.065190e-02           inf
std              6.336545e+00           6.992269e+00           NaN
min              0.000000e+00           0.000000e+00  0.000000e+00
25%              0.000000e+00           0.000000e+00  1.472000e+09
50%              0.000000e+00           0.000000e+00  2.944000e+09
75%              0.000000e+00           0.000000e+00  2.944000e+09
max              3.269767e+03           2.848743e+03           inf

       Flow Packets/s  Flow IAT Mean  Flow IAT Std  Flow IAT Max  \
count    5.074413e+06   5.074413e+06  5.074413e+06  5.074413e+06
mean              inf   3.858445e+02  8.211467e+02  3.161658e+03
std               NaN   5.956067e+04  1.047141e+05  3.716702e+05
min      3.929703e-02   0.000000e+00  0.000000e+00  0.000000e+00
25%      1.000000e+06   1.000000e+00  0.000000e+00  1.000000e+00
50%      2.000000e+06   1.000000e+00  0.000000e+00  1.000000e+00
75%      2.000000e+06   2.000000e+00  0.000000e+00  2.000000e+00
max               inf   4.505603e+07  5.876782e+07  1.199384e+08

       Flow IAT Min  Fwd IAT Total  Fwd IAT Mean   Fwd IAT Std   Fwd IAT Max  \
count  5.074413e+06   5.074413e+06  5.074413e+06  5.074413e+06  5.074413e+06
mean   7.580827e+01   6.841976e+03  4.924365e+02  9.267230e+02  2.969594e+03
std    4.011741e+04   7.617601e+05  6.828788e+04  1.215047e+05  3.649128e+05
min    0.000000e+00   0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
25%    1.000000e+00   1.000000e+00  1.000000e+00  0.000000e+00  1.000000e+00
50%    1.000000e+00   1.000000e+00  1.000000e+00  0.000000e+00  1.000000e+00
75%    2.000000e+00   2.000000e+00  2.000000e+00  0.000000e+00  2.000000e+00
max    4.505603e+07   1.199999e+08  4.505603e+07  5.876782e+07  1.199384e+08

        Fwd IAT Min  Bwd IAT Total  Bwd IAT Mean   Bwd IAT Std   Bwd IAT Max  \
count  5.074413e+06   5.074413e+06  5.074413e+06  5.074413e+06  5.074413e+06
mean   7.474153e+01   4.814705e+03  3.279090e+02  6.886307e+02  2.004077e+03
std    4.011755e+04   6.379946e+05  5.375593e+04  1.072985e+05  2.994759e+05
min    0.000000e+00   0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
25%    1.000000e+00   0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
50%    1.000000e+00   0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
75%    2.000000e+00   0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
max    4.505603e+07   1.199999e+08  4.975526e+07  7.036456e+07  9.951052e+07

        Bwd IAT Min  Fwd PSH Flags  Bwd PSH Flags  Fwd URG Flags  \
count  5.074413e+06   5.074413e+06      5074413.0      5074413.0
mean   1.909580e-03   1.186344e-04            0.0            0.0
std    2.893508e-01   1.089130e-02            0.0            0.0
min    0.000000e+00   0.000000e+00            0.0            0.0
25%    0.000000e+00   0.000000e+00            0.0            0.0
50%    0.000000e+00   0.000000e+00            0.0            0.0
75%    0.000000e+00   0.000000e+00            0.0            0.0
max    2.380000e+02   1.000000e+00            0.0            0.0

       Bwd URG Flags  Fwd Header Length  Bwd Header Length  Fwd Packets/s  \
count      5074413.0       5.074413e+06       5.074413e+06   5.074413e+06
mean             0.0      -1.085312e+08      -1.675223e+03   1.499485e+06
std              0.0       2.502183e+09       1.887059e+06   7.636311e+05
min              0.0      -2.529271e+11      -2.125438e+09   0.000000e+00
25%              0.0      -2.000000e+00       0.000000e+00   1.000000e+06
50%              0.0       0.000000e+00       0.000000e+00   2.000000e+06
75%              0.0       2.800000e+01       0.000000e+00   2.000000e+06
max              0.0       1.559380e+05       1.472800e+05   4.000000e+06

       Bwd Packets/s  Min Packet Length  Max Packet Length  \
count   5.074413e+06       5.074413e+06       5.074413e+06
mean    7.204761e+00       1.377607e+03       1.378091e+03
std     2.522208e+03       3.004869e+02       3.006066e+02
min     0.000000e+00       0.000000e+00       0.000000e+00
25%     0.000000e+00       1.464000e+03       1.464000e+03
50%     0.000000e+00       1.472000e+03       1.472000e+03
75%     0.000000e+00       1.472000e+03       1.472000e+03
max     2.000000e+06       1.472000e+03       3.358000e+04

       Packet Length Mean  Packet Length Std  Packet Length Variance  \
count        5.074413e+06       5.074413e+06            5.074413e+06
mean         1.377849e+03       1.087520e-01            5.173643e+01
std          2.996167e+02       7.191983e+00            7.135429e+03
min          0.000000e+00       0.000000e+00            0.000000e+00
25%          1.464000e+03       0.000000e+00            0.000000e+00
50%          1.472000e+03       0.000000e+00            0.000000e+00
75%          1.472000e+03       0.000000e+00            0.000000e+00
max          2.662265e+03       2.866281e+03            8.215564e+06

       FIN Flag Count  SYN Flag Count  RST Flag Count  PSH Flag Count  \
count       5074413.0    5.074413e+06    5.074413e+06       5074413.0
mean              0.0    1.182403e-05    1.186344e-04             0.0
std               0.0    3.438588e-03    1.089130e-02             0.0
min               0.0    0.000000e+00    0.000000e+00             0.0
25%               0.0    0.000000e+00    0.000000e+00             0.0
50%               0.0    0.000000e+00    0.000000e+00             0.0
75%               0.0    0.000000e+00    0.000000e+00             0.0
max               0.0    1.000000e+00    1.000000e+00             0.0

       ACK Flag Count  URG Flag Count  CWE Flag Count  ECE Flag Count  \
count    5.074413e+06    5.074413e+06    5.074413e+06       5074413.0
mean     1.915492e-04    4.737494e-04    2.477134e-04             0.0
std      1.383881e-02    2.176063e-02    1.573697e-02             0.0
min      0.000000e+00    0.000000e+00    0.000000e+00             0.0
25%      0.000000e+00    0.000000e+00    0.000000e+00             0.0
50%      0.000000e+00    0.000000e+00    0.000000e+00             0.0
75%      0.000000e+00    0.000000e+00    0.000000e+00             0.0
max      1.000000e+00    1.000000e+00    1.000000e+00             0.0

       Down/Up Ratio  Average Packet Size  Avg Fwd Segment Size  \
count   5.074413e+06         5.074413e+06          5.074413e+06
mean    7.894509e-04         2.066026e+03          1.377831e+03
std     3.884471e-02         4.512524e+02          2.996888e+02
min     0.000000e+00         0.000000e+00          0.000000e+00
25%     0.000000e+00         2.196000e+03          1.464000e+03
50%     0.000000e+00         2.208000e+03          1.472000e+03
75%     0.000000e+00         2.208000e+03          1.472000e+03
max     1.300000e+01         2.663433e+03          3.015291e+03

       Avg Bwd Segment Size  Fwd Header Length.1  Fwd Avg Bytes/Bulk  \
count          5.074413e+06         5.074413e+06           5074413.0
mean           7.309350e-02        -1.085312e+08                 0.0
std            6.336545e+00         2.502183e+09                 0.0
min            0.000000e+00        -2.529271e+11                 0.0
25%            0.000000e+00        -2.000000e+00                 0.0
50%            0.000000e+00         0.000000e+00                 0.0
75%            0.000000e+00         2.800000e+01                 0.0
max            3.269767e+03         1.559380e+05                 0.0

       Fwd Avg Packets/Bulk  Fwd Avg Bulk Rate  Bwd Avg Bytes/Bulk  \
count             5074413.0          5074413.0           5074413.0
mean                    0.0                0.0                 0.0
std                     0.0                0.0                 0.0
min                     0.0                0.0                 0.0
25%                     0.0                0.0                 0.0
50%                     0.0                0.0                 0.0
75%                     0.0                0.0                 0.0
max                     0.0                0.0                 0.0

       Bwd Avg Packets/Bulk  Bwd Avg Bulk Rate  Subflow Fwd Packets  \
count             5074413.0          5074413.0         5.074413e+06
mean                    0.0                0.0         6.013596e+00
std                     0.0                0.0         5.953501e+02
min                     0.0                0.0         1.000000e+00
25%                     0.0                0.0         2.000000e+00
50%                     0.0                0.0         2.000000e+00
75%                     0.0                0.0         2.000000e+00
max                     0.0                0.0         1.001480e+05

       Subflow Fwd Bytes  Subflow Bwd Packets  Subflow Bwd Bytes  \
count       5.074413e+06         5.074413e+06       5.074413e+06
mean        2.952438e+03         8.004867e-03       6.768139e+00
std         9.122037e+03         2.950822e+00       6.837585e+03
min         0.000000e+00         0.000000e+00       0.000000e+00
25%         2.928000e+03         0.000000e+00       0.000000e+00
50%         2.944000e+03         0.000000e+00       0.000000e+00
75%         2.944000e+03         0.000000e+00       0.000000e+00
max         1.526642e+07         4.602000e+03       1.099376e+07

       Init_Win_bytes_forward  Init_Win_bytes_backward  act_data_pkt_fwd  \
count            5.074413e+06             5.074413e+06      5.074413e+06
mean             6.901152e+00             1.532372e+00      1.434766e+00
std              6.055634e+02             2.954216e+02      9.481883e+00
min             -1.000000e+00            -1.000000e+00      0.000000e+00
25%             -1.000000e+00            -1.000000e+00      1.000000e+00
50%             -1.000000e+00            -1.000000e+00      1.000000e+00
75%             -1.000000e+00            -1.000000e+00      1.000000e+00
max              6.553500e+04             6.424000e+04      5.043000e+03

       min_seg_size_forward   Active Mean    Active Std    Active Max  \
count          5.074413e+06  5.074413e+06  5.074413e+06  5.074413e+06
mean          -3.680966e+07  6.703219e+01  1.305199e+01  8.437979e+01
std            1.943476e+08  2.653840e+04  6.162152e+03  2.883959e+04
min           -1.408238e+09  0.000000e+00  0.000000e+00  0.000000e+00
25%           -1.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
50%            0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
75%            1.400000e+01  0.000000e+00  0.000000e+00  0.000000e+00
max            1.480000e+03  4.872242e+07  7.827056e+06  4.872242e+07

         Active Min     Idle Mean      Idle Std      Idle Max      Idle Min  \
count  5.074413e+06  5.074413e+06  5.074413e+06  5.074413e+06  5.074413e+06
mean   5.788418e+01  2.331791e+03  1.054355e+02  2.420004e+03  2.240776e+03
std    2.557915e+04  3.318188e+05  4.571781e+04  3.434160e+05  3.242934e+05
min    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
25%    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
50%    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
75%    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
max    4.872242e+07  1.017888e+08  6.600292e+07  1.037700e+08  1.017888e+08

            Inbound
count  5.074413e+06
mean   9.990669e-01
std    3.053264e-02
min    0.000000e+00
25%    1.000000e+00
50%    1.000000e+00
75%    1.000000e+00
max    1.000000e+00

In [5]:
print(df['Timestamp'].head(20))

0     2018-12-01 10:51:39.813448
1     2018-12-01 10:51:39.820842
2     2018-12-01 10:51:39.852499
3     2018-12-01 10:51:39.890213
4     2018-12-01 10:51:39.941151
5     2018-12-01 10:51:39.942030
6     2018-12-01 10:51:39.973650
7     2018-12-01 10:51:39.994394
8     2018-12-01 10:51:40.005191
9     2018-12-01 10:51:40.036581
10    2018-12-01 10:51:40.046017
11    2018-12-01 10:51:40.067060
12    2018-12-01 10:51:40.086605
13    2018-12-01 10:51:40.151799
14    2018-12-01 10:51:40.169437
15    2018-12-01 10:51:40.181161
16    2018-12-01 10:51:40.200131
17    2018-12-01 10:51:40.212271
18    2018-12-01 10:51:40.218232
19    2018-12-01 10:51:40.231291
Name: Timestamp, dtype: object

In [9]:
#Convert string dates to actual dates
df['Timestamp'] = pd.to_datetime(df['Timestamp'])

#Set time periods we will record
attack_start = pd.Timestamp('2018-12-01 10:52:00')
attack_end   = pd.Timestamp('2018-12-01 11:05:00')
normal_start = pd.Timestamp('2018-12-01 10:30:00')

#filter dataset to begin at normal start
df_filtered = df[df['Timestamp'] >= normal_start]

# This shows us how many normal vs attack rows we kept
print(df_filtered['Label'].value_counts())

# This shows how many rows we kept vs the original 5 million
print(f"Rows kept: {len(df_filtered)} out of {len(df)}")

Label
DrDoS_DNS    5071011
BENIGN          3402
Name: count, dtype: int64
Rows kept: 5074413 out of 5074413

In [8]:
df['Timestamp'] = pd.to_datetime(df['Timestamp'])
print(df['Timestamp'].dtype)
print(df['Timestamp'].head())
print(df['Timestamp'].min())
print(df['Timestamp'].max())

datetime64[ns]
0   2018-12-01 10:51:39.813448
1   2018-12-01 10:51:39.820842
2   2018-12-01 10:51:39.852499
3   2018-12-01 10:51:39.890213
4   2018-12-01 10:51:39.941151
Name: Timestamp, dtype: datetime64[ns]
2018-12-01 10:51:39.813448
2018-12-01 11:22:40.254719

In [5]:
# ── LDAP Dataset
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option('display.max_columns', None)
df_ldap = pd.read_csv("DrDoS_LDAP.csv")

df_ldap.columns = df_ldap.columns.str.strip()

df_ldap.head()

C:\Users\tenda\AppData\Local\Temp\ipykernel_6972\378537816.py:8: DtypeWarning: Columns (85) have mixed types. Specify dtype option on import or set low_memory=False.
  df_ldap = pd.read_csv("DrDoS_LDAP.csv")

,Unnamed: 0,Flow ID,Source IP,Source Port,Destination IP,Destination Port,Protocol,Timestamp,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,Bwd Packet Length Max,Bwd Packet Length Min,Bwd Packet Length Mean,Bwd Packet Length Std,Flow Bytes/s,Flow Packets/s,Flow IAT Mean,Flow IAT Std,Flow IAT Max,Flow IAT Min,Fwd IAT Total,Fwd IAT Mean,Fwd IAT Std,Fwd IAT Max,Fwd IAT Min,Bwd IAT Total,Bwd IAT Mean,Bwd IAT Std,Bwd IAT Max,Bwd IAT Min,Fwd PSH Flags,Bwd PSH Flags,Fwd URG Flags,Bwd URG Flags,Fwd Header Length,Bwd Header Length,Fwd Packets/s,Bwd Packets/s,Min Packet Length,Max Packet Length,Packet Length Mean,Packet Length Std,Packet Length Variance,FIN Flag Count,SYN Flag Count,RST Flag Count,PSH Flag Count,ACK Flag Count,URG Flag Count,CWE Flag Count,ECE Flag Count,Down/Up Ratio,Average Packet Size,Avg Fwd Segment Size,Avg Bwd Segment Size,Fwd Header Length.1,Fwd Avg Bytes/Bulk,Fwd Avg Packets/Bulk,Fwd Avg Bulk Rate,Bwd Avg Bytes/Bulk,Bwd Avg Packets/Bulk,Bwd Avg Bulk Rate,Subflow Fwd Packets,Subflow Fwd Bytes,Subflow Bwd Packets,Subflow Bwd Bytes,Init_Win_bytes_forward,Init_Win_bytes_backward,act_data_pkt_fwd,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,SimillarHTTP,Inbound,Label
0,21010,172.16.0.5-192.168.50.1-0-0-0,172.16.0.5,0,192.168.50.1,0,0,2018-12-01 11:22:40.254769,9141643,85894,28,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,9.398967e+03,106.39591,209.905159,2968.0,0.0,9141643.0,106.430594,209.94653,2968.0,0.0,8487477.0,314351.0,1.147263e+06,5975703.0,0.0,0,0,0,0,0,0,9.395904e+03,3.062907,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0,0,0,0,0,0,0,85894,0,28,0,-1,-1,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,DrDoS_LDAP
1,20932,172.16.0.5-192.168.50.1-900-1808-17,172.16.0.5,900,192.168.50.1,1808,17,2018-12-01 11:22:40.255361,1,2,0,2944.0,0.0,1472.0,1472.0,1472.0,0.0,0.0,0.0,0.0,0.0,2.944000e+09,2.000000e+06,1.00000,0.000000,1.0,1.0,1.0,1.000000,0.00000,1.0,1.0,0.0,0.0,0.000000e+00,0.0,0.0,0,0,0,0,-2,0,2.000000e+06,0.000000,1472.0,1472.0,1472.0,0.0,0.0,0,0,0,0,0,0,0,0,0.0,2208.0,1472.0,0.0,-2,0,0,0,0,0,0,2,2944,0,0,-1,-1,1,-1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,DrDoS_LDAP
2,27876,172.16.0.5-192.168.50.1-900-58766-17,172.16.0.5,900,192.168.50.1,58766,17,2018-12-01 11:22:40.255568,2,2,0,2944.0,0.0,1472.0,1472.0,1472.0,0.0,0.0,0.0,0.0,0.0,1.472000e+09,1.000000e+06,2.00000,0.000000,2.0,2.0,2.0,2.000000,0.00000,2.0,2.0,0.0,0.0,0.000000e+00,0.0,0.0,0,0,0,0,-2,0,1.000000e+06,0.000000,1472.0,1472.0,1472.0,0.0,0.0,0,0,0,0,0,0,0,0,0.0,2208.0,1472.0,0.0,-2,0,0,0,0,0,0,2,2944,0,0,-1,-1,1,-1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,DrDoS_LDAP
3,24270,172.16.0.5-192.168.50.1-900-35228-17,172.16.0.5,900,192.168.50.1,35228,17,2018-12-01 11:22:40.256113,1,2,0,2944.0,0.0,1472.0,1472.0,1472.0,0.0,0.0,0.0,0.0,0.0,2.944000e+09,2.000000e+06,1.00000,0.000000,1.0,1.0,1.0,1.000000,0.00000,1.0,1.0,0.0,0.0,0.000000e+00,0.0,0.0,0,0,0,0,-2,0,2.000000e+06,0.000000,1472.0,1472.0,1472.0,0.0,0.0,0,0,0,0,0,0,0,0,0.0,2208.0,1472.0,0.0,-2,0,0,0,0,0,0,2,2944,0,0,-1,-1,1,-1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,DrDoS_LDAP
4,5109,172.16.0.5-192.168.50.1-900-44969-17,172.16.0.5,900,192.168.50.1,44969,17,2018-12-01 11:22:40.256285,2,2,0,2944.0,0.0,1472.0,1472.0,1472.0,0.0,0.0,0.0,0.0,0.0,1.472000e+09,1.000000e+06,2.00000,0.000000,2.0,2.0,2.0,2.000000,0.00000,2.0,2.0,0.0,0.0,0.000000e+00,0.0,0.0,0,0,0,0,-2,0,1.000000e+06,0.000000,1472.0,1472.0,1472.0,0.0,0.0,0,0,0,0,0,0,0,0,0.0,2208.0,1472.0,0.0,-2,0,0,0,0,0,0,2,2944,0,0,-1,-1,1,-1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,DrDoS_LDAP

In [15]:
# Shape of the dataset (rows, columns)
print(df_ldap.shape)

# Data type of each column
print(df_ldap.dtypes)

# Count of normal vs attack traffic rows
print(df_ldap['Label'].value_counts())

(2181542, 88)
Unnamed: 0          int64
Flow ID            object
Source IP          object
Source Port         int64
Destination IP     object
                   ...
Idle Max          float64
Idle Min          float64
SimillarHTTP       object
Inbound             int64
Label              object
Length: 88, dtype: object
Label
DrDoS_LDAP    2179930
BENIGN           1612
Name: count, dtype: int64

In [17]:
# Check for missing values in each column
print(df_ldap.isnull().sum())

# Summary statistics for all numeric columns
print(df_ldap.describe())

Unnamed: 0        0
Flow ID           0
Source IP         0
Source Port       0
Destination IP    0
                 ..
Idle Max          0
Idle Min          0
SimillarHTTP      0
Inbound           0
Label             0
Length: 88, dtype: int64
         Unnamed: 0   Source Port  Destination Port      Protocol  \
count  2.181542e+06  2.181542e+06      2.181542e+06  2.181542e+06
mean   1.704283e+04  8.531110e+02      3.276972e+04  1.699132e+01
min    0.000000e+00  0.000000e+00      0.000000e+00  0.000000e+00
25%    8.521000e+03  6.610000e+02      1.640000e+04  1.700000e+01
50%    1.704300e+04  8.110000e+02      3.277200e+04  1.700000e+01
75%    2.556400e+04  9.000000e+02      4.915900e+04  1.700000e+01
max    3.420300e+04  6.551000e+04      6.553500e+04  1.700000e+01
std    9.840009e+03  1.947001e+03      1.892384e+04  3.242059e-01

                           Timestamp  Flow Duration  Total Fwd Packets  \
count                        2181542   2.181542e+06       2.181542e+06
mean   2018-12-01 11:27:31.234316032   6.698804e+02       4.524823e+00
min       2018-12-01 11:22:40.254769   0.000000e+00       1.000000e+00
25%    2018-12-01 11:25:04.209382144   1.000000e+00       2.000000e+00
50%    2018-12-01 11:27:27.116924928   1.000000e+00       2.000000e+00
75%    2018-12-01 11:29:58.105404416   2.000000e+00       2.000000e+00
max       2018-12-01 11:32:32.915361   1.116618e+07       8.622100e+04
std                              NaN   6.448156e+04       4.648172e+02

       Total Backward Packets  Total Length of Fwd Packets  \
count            2.181542e+06                 2.181542e+06
mean             3.328380e-03                 2.933517e+03
min              0.000000e+00                 0.000000e+00
25%              0.000000e+00                 2.944000e+03
50%              0.000000e+00                 2.944000e+03
75%              0.000000e+00                 2.944000e+03
max              1.810000e+02                 5.888000e+04
std              2.942144e-01                 3.031092e+02

       Total Length of Bwd Packets  Fwd Packet Length Max  \
count                 2.181542e+06           2.181542e+06
mean                  9.575672e-01           1.462711e+03
min                   0.000000e+00           0.000000e+00
25%                   0.000000e+00           1.472000e+03
50%                   0.000000e+00           1.472000e+03
75%                   0.000000e+00           1.472000e+03
max                   1.746340e+05           2.980000e+03
std                   2.451018e+02           6.399144e+01

       Fwd Packet Length Min  Fwd Packet Length Mean  Fwd Packet Length Std  \
count           2.181542e+06            2.181542e+06           2.181542e+06
mean            1.462645e+03            1.462662e+03           2.528185e-02
min             0.000000e+00            0.000000e+00           0.000000e+00
25%             1.472000e+03            1.472000e+03           0.000000e+00
50%             1.472000e+03            1.472000e+03           0.000000e+00
75%             1.472000e+03            1.472000e+03           0.000000e+00
max             1.472000e+03            1.895333e+03           1.246804e+03
std             6.486234e+01            6.453368e+01           3.188758e+00

       Bwd Packet Length Max  Bwd Packet Length Min  Bwd Packet Length Mean  \
count           2.181542e+06           2.181542e+06            2.181542e+06
mean            1.696126e-01           1.986806e-02            5.992503e-02
min             0.000000e+00           0.000000e+00            0.000000e+00
25%             0.000000e+00           0.000000e+00            0.000000e+00
50%             0.000000e+00           0.000000e+00            0.000000e+00
75%             0.000000e+00           0.000000e+00            0.000000e+00
max             3.452000e+03           1.072000e+03            1.997895e+03
std             1.903090e+01           1.679826e+00            5.754805e+00

       Bwd Packet Length Std  Flow Bytes/s  Flow Packets/s  Flow IAT Mean  \
count           2.181542e+06  2.181530e+06    2.181542e+06   2.181542e+06
mean            5.125597e-02           inf             inf   8.313135e+01
min             0.000000e+00  0.000000e+00    3.432401e-01   0.000000e+00
25%             0.000000e+00  1.472000e+09    1.000000e+06   1.000000e+00
50%             0.000000e+00  2.944000e+09    2.000000e+06   1.000000e+00
75%             0.000000e+00  2.944000e+09    2.000000e+06   2.000000e+00
max             1.256880e+03           inf             inf   5.826825e+06
std             6.183369e+00           NaN             NaN   1.027942e+04

       Flow IAT Std  Flow IAT Max  Flow IAT Min  Fwd IAT Total  Fwd IAT Mean  \
count  2.181542e+06  2.181542e+06  2.181542e+06   2.181542e+06  2.181542e+06
mean   1.293919e+02  3.185653e+02  1.612167e+01   5.964555e+02  8.655956e+01
min    0.000000e+00  0.000000e+00  0.000000e+00   0.000000e+00  0.000000e+00
25%    0.000000e+00  1.000000e+00  1.000000e+00   1.000000e+00  1.000000e+00
50%    0.000000e+00  1.000000e+00  1.000000e+00   1.000000e+00  1.000000e+00
75%    0.000000e+00  2.000000e+00  2.000000e+00   2.000000e+00  2.000000e+00
max    4.410699e+06  9.258158e+06  5.826825e+06   1.116618e+07  5.826825e+06
std    1.511867e+04  3.338042e+04  6.102717e+03   6.207235e+04  1.130774e+04

        Fwd IAT Std   Fwd IAT Max   Fwd IAT Min  Bwd IAT Total  Bwd IAT Mean  \
count  2.181542e+06  2.181542e+06  2.181542e+06   2.181542e+06  2.181542e+06
mean   1.224467e+02  2.649936e+02  1.567049e+01   2.974815e+02  3.431838e+01
min    0.000000e+00  0.000000e+00  0.000000e+00   0.000000e+00  0.000000e+00
25%    0.000000e+00  1.000000e+00  1.000000e+00   0.000000e+00  0.000000e+00
50%    0.000000e+00  1.000000e+00  1.000000e+00   0.000000e+00  0.000000e+00
75%    0.000000e+00  2.000000e+00  2.000000e+00   0.000000e+00  0.000000e+00
max    4.410699e+06  9.258158e+06  5.826825e+06   9.999950e+06  2.502546e+06
std    1.586616e+04  3.058451e+04  6.099844e+03   3.878305e+04  4.908983e+03

        Bwd IAT Std   Bwd IAT Max   Bwd IAT Min  Fwd PSH Flags  Bwd PSH Flags  \
count  2.181542e+06  2.181542e+06  2.181542e+06   2.181542e+06      2181542.0
mean   6.238946e+01  1.682394e+02  4.379013e-03   1.145978e-04            0.0
min    0.000000e+00  0.000000e+00  0.000000e+00   0.000000e+00            0.0
25%    0.000000e+00  0.000000e+00  0.000000e+00   0.000000e+00            0.0
50%    0.000000e+00  0.000000e+00  0.000000e+00   0.000000e+00            0.0
75%    0.000000e+00  0.000000e+00  0.000000e+00   0.000000e+00            0.0
max    3.539069e+06  7.212760e+06  2.490000e+02   1.000000e+00            0.0
std    8.807918e+03  2.392110e+04  4.801843e-01   1.070443e-02            0.0

       Fwd URG Flags  Bwd URG Flags  Fwd Header Length  Bwd Header Length  \
count      2181542.0      2181542.0       2.181542e+06       2.181542e+06
mean             0.0            0.0      -1.046861e+08      -8.768449e+03
min              0.0            0.0      -2.550526e+10      -2.125438e+09
25%              0.0            0.0       0.000000e+00       0.000000e+00
50%              0.0            0.0       1.600000e+01       0.000000e+00
75%              0.0            0.0       4.000000e+01       0.000000e+00
max              0.0            0.0       5.328000e+04       3.644000e+03
std              0.0            0.0       4.621957e+08       4.317050e+06

       Fwd Packets/s  Bwd Packets/s  Min Packet Length  Max Packet Length  \
count   2.181542e+06   2.181542e+06       2.181542e+06       2.181542e+06
mean    1.531080e+06   4.946082e+00       1.462644e+03       1.462821e+03
min     0.000000e+00   0.000000e+00       0.000000e+00       0.000000e+00
25%     1.000000e+06   0.000000e+00       1.472000e+03       1.472000e+03
50%     2.000000e+06   0.000000e+00       1.472000e+03       1.472000e+03
75%     2.000000e+06   0.000000e+00       1.472000e+03       1.472000e+03
max     3.000000e+06   1.000000e+06       1.472000e+03       3.452000e+03
std     6.732873e+05   1.699922e+03       6.488578e+01       6.392595e+01

       Packet Length Mean  Packet Length Std  Packet Length Variance  \
count        2.181542e+06       2.181542e+06            2.181542e+06
mean         1.462679e+03       5.275343e-02            2.876137e+01
min          0.000000e+00       0.000000e+00            0.000000e+00
25%          1.472000e+03       0.000000e+00            0.000000e+00
50%          1.472000e+03       0.000000e+00            0.000000e+00
75%          1.472000e+03       0.000000e+00            0.000000e+00
max          1.650435e+03       1.255980e+03            1.577485e+06
std          6.420599e+01       5.362705e+00            4.238625e+03

       FIN Flag Count  SYN Flag Count  RST Flag Count  PSH Flag Count  \
count       2181542.0    2.181542e+06    2.181542e+06       2181542.0
mean              0.0    3.117061e-05    1.145978e-04             0.0
min               0.0    0.000000e+00    0.000000e+00             0.0
25%               0.0    0.000000e+00    0.000000e+00             0.0
50%               0.0    0.000000e+00    0.000000e+00             0.0
75%               0.0    0.000000e+00    0.000000e+00             0.0
max               0.0    1.000000e+00    1.000000e+00             0.0
std               0.0    5.582979e-03    1.070443e-02             0.0

       ACK Flag Count  URG Flag Count  CWE Flag Count  ECE Flag Count  \
count    2.181542e+06    2.181542e+06    2.181542e+06       2181542.0
mean     1.714384e-04    4.891036e-04    1.182650e-04             0.0
min      0.000000e+00    0.000000e+00    0.000000e+00             0.0
25%      0.000000e+00    0.000000e+00    0.000000e+00             0.0
50%      0.000000e+00    0.000000e+00    0.000000e+00             0.0
75%      0.000000e+00    0.000000e+00    0.000000e+00             0.0
max      1.000000e+00    1.000000e+00    1.000000e+00             0.0
std      1.309233e-02    2.211028e-02    1.087433e-02             0.0

       Down/Up Ratio  Average Packet Size  Avg Fwd Segment Size  \
count   2.181542e+06         2.181542e+06          2.181542e+06
mean    5.968255e-04         2.193328e+03          1.462662e+03
min     0.000000e+00         0.000000e+00          0.000000e+00
25%     0.000000e+00         2.208000e+03          1.472000e+03
50%     0.000000e+00         2.208000e+03          1.472000e+03
75%     0.000000e+00         2.208000e+03          1.472000e+03
max     1.000000e+01         2.208000e+03          1.895333e+03
std     2.950572e-02         9.800888e+01          6.453368e+01

       Avg Bwd Segment Size  Fwd Header Length.1  Fwd Avg Bytes/Bulk  \
count          2.181542e+06         2.181542e+06           2181542.0
mean           5.992503e-02        -1.046861e+08                 0.0
min            0.000000e+00        -2.550526e+10                 0.0
25%            0.000000e+00         0.000000e+00                 0.0
50%            0.000000e+00         1.600000e+01                 0.0
75%            0.000000e+00         4.000000e+01                 0.0
max            1.997895e+03         5.328000e+04                 0.0
std            5.754805e+00         4.621957e+08                 0.0

       Fwd Avg Packets/Bulk  Fwd Avg Bulk Rate  Bwd Avg Bytes/Bulk  \
count             2181542.0          2181542.0           2181542.0
mean                    0.0                0.0                 0.0
min                     0.0                0.0                 0.0
25%                     0.0                0.0                 0.0
50%                     0.0                0.0                 0.0
75%                     0.0                0.0                 0.0
max                     0.0                0.0                 0.0
std                     0.0                0.0                 0.0

       Bwd Avg Packets/Bulk  Bwd Avg Bulk Rate  Subflow Fwd Packets  \
count             2181542.0          2181542.0         2.181542e+06
mean                    0.0                0.0         4.524823e+00
min                     0.0                0.0         1.000000e+00
25%                     0.0                0.0         2.000000e+00
50%                     0.0                0.0         2.000000e+00
75%                     0.0                0.0         2.000000e+00
max                     0.0                0.0         8.622100e+04
std                     0.0                0.0         4.648172e+02

       Subflow Fwd Bytes  Subflow Bwd Packets  Subflow Bwd Bytes  \
count       2.181542e+06         2.181542e+06       2.181542e+06
mean        2.933517e+03         3.328380e-03       9.575672e-01
min         0.000000e+00         0.000000e+00       0.000000e+00
25%         2.944000e+03         0.000000e+00       0.000000e+00
50%         2.944000e+03         0.000000e+00       0.000000e+00
75%         2.944000e+03         0.000000e+00       0.000000e+00
max         5.888000e+04         1.810000e+02       1.746340e+05
std         3.031092e+02         2.942144e-01       2.451018e+02

       Init_Win_bytes_forward  Init_Win_bytes_backward  act_data_pkt_fwd  \
count            2.181542e+06             2.181542e+06      2.181542e+06
mean             6.856333e+00             1.161201e+00      1.005629e+00
min             -1.000000e+00            -1.000000e+00      0.000000e+00
25%             -1.000000e+00            -1.000000e+00      1.000000e+00
50%             -1.000000e+00            -1.000000e+00      1.000000e+00
75%             -1.000000e+00            -1.000000e+00      1.000000e+00
max              6.553500e+04             6.553500e+04      9.600000e+01
std              5.545155e+02             2.663984e+02      2.152441e-01

       min_seg_size_forward   Active Mean  Active Std    Active Max  \
count          2.181542e+06  2.181542e+06   2181542.0  2.181542e+06
mean          -5.237284e+07  9.434153e-03         0.0  9.434153e-03
min           -1.408238e+09  0.000000e+00         0.0  0.000000e+00
25%            0.000000e+00  0.000000e+00         0.0  0.000000e+00
50%            8.000000e+00  0.000000e+00         0.0  0.000000e+00
75%            2.000000e+01  0.000000e+00         0.0  0.000000e+00
max            1.480000e+03  2.046800e+04         0.0  2.046800e+04
std            2.300741e+08  1.385786e+01         0.0  1.385786e+01

         Active Min     Idle Mean   Idle Std      Idle Max      Idle Min  \
count  2.181542e+06  2.181542e+06  2181542.0  2.181542e+06  2.181542e+06
mean   9.434153e-03  3.613463e+01        0.0  3.613463e+01  3.613463e+01
min    0.000000e+00  0.000000e+00        0.0  0.000000e+00  0.000000e+00
25%    0.000000e+00  0.000000e+00        0.0  0.000000e+00  0.000000e+00
50%    0.000000e+00  0.000000e+00        0.0  0.000000e+00  0.000000e+00
75%    0.000000e+00  0.000000e+00        0.0  0.000000e+00  0.000000e+00
max    2.046800e+04  9.258158e+06        0.0  9.258158e+06  9.258158e+06
std    1.385786e+01  1.565532e+04        0.0  1.565532e+04  1.565532e+04

            Inbound
count  2.181542e+06
mean   9.990319e-01
min    0.000000e+00
25%    1.000000e+00
50%    1.000000e+00
75%    1.000000e+00
max    1.000000e+00
std    3.109961e-02

In [19]:
# Preview the first 20 timestamp values to check format
print(df_ldap['Timestamp'].head(20))

0    2018-12-01 11:22:40.254769
1    2018-12-01 11:22:40.255361
2    2018-12-01 11:22:40.255568
3    2018-12-01 11:22:40.256113
4    2018-12-01 11:22:40.256285
5    2018-12-01 11:22:40.257136
6    2018-12-01 11:22:40.257355
7    2018-12-01 11:22:40.257486
8    2018-12-01 11:22:40.257691
9    2018-12-01 11:22:40.258017
10   2018-12-01 11:22:40.258453
11   2018-12-01 11:22:40.258759
12   2018-12-01 11:22:40.259376
13   2018-12-01 11:22:40.259765
14   2018-12-01 11:22:40.259884
15   2018-12-01 11:22:40.260596
16   2018-12-01 11:22:40.260741
17   2018-12-01 11:22:40.260938
18   2018-12-01 11:22:40.261864
19   2018-12-01 11:22:40.262339
Name: Timestamp, dtype: datetime64[ns]

In [20]:
# Convert Timestamp column to datetime format
df_ldap['Timestamp'] = pd.to_datetime(df_ldap['Timestamp'])

# Define LDAP attack and normal traffic time boundaries
ldap_attack_start = pd.Timestamp('2018-12-01 11:22:00')
ldap_attack_end   = pd.Timestamp('2018-12-01 11:32:00')
ldap_normal_start = pd.Timestamp('2018-12-01 11:00:00')  # start before attack

# Filter dataset to only include rows from normal_start onwards
df_ldap_filtered = df_ldap[df_ldap['Timestamp'] >= ldap_normal_start]

# Check how many normal vs attack rows we kept
print(df_ldap_filtered['Label'].value_counts())

# Compare filtered row count to original
print(f"Rows kept: {len(df_ldap_filtered)} out of {len(df_ldap)}")

Label
DrDoS_LDAP    2179930
BENIGN           1612
Name: count, dtype: int64
Rows kept: 2181542 out of 2181542

In [21]:
# Confirm Timestamp column is now datetime type
print(df_ldap['Timestamp'].dtype)

# Preview the first couple of timestamps
print(df_ldap['Timestamp'].head())

# Earliest timestamp in the dataset
print(df_ldap['Timestamp'].min())

# Latest timestamp in the dataset
print(df_ldap['Timestamp'].max())

datetime64[ns]
0   2018-12-01 11:22:40.254769
1   2018-12-01 11:22:40.255361
2   2018-12-01 11:22:40.255568
3   2018-12-01 11:22:40.256113
4   2018-12-01 11:22:40.256285
Name: Timestamp, dtype: datetime64[ns]
2018-12-01 11:22:40.254769
2018-12-01 11:32:32.915361

In [23]:
# Compare normal vs attack traffic stats
print(ldap_normal.describe())
print(ldap_attack.describe())

         Unnamed: 0   Source Port  Destination Port     Protocol  \
count   1612.000000   1612.000000       1612.000000  1612.000000
mean   13703.068859  44437.626551       7797.823201     8.442928
min        0.000000      0.000000          0.000000     0.000000
25%      462.250000  50535.500000         53.000000     6.000000
50%    12730.000000  57247.000000         80.000000     6.000000
75%    24202.500000  59389.250000        443.000000    17.000000
max    34153.000000  65510.000000      60271.000000    17.000000
std    11729.781379  24127.259570      19457.849608     5.474604

                           Timestamp  Flow Duration  Total Fwd Packets  \
count                           1612   1.612000e+03        1612.000000
mean   2018-12-01 11:27:46.324185088   2.637909e+05           3.913772
min       2018-12-01 11:22:40.970628   0.000000e+00           1.000000
25%    2018-12-01 11:25:32.068581120   9.800000e+01           2.000000
50%    2018-12-01 11:27:29.369863936   2.088400e+04           2.000000
75%    2018-12-01 11:30:25.461929728   5.490725e+04           3.000000
max       2018-12-01 11:32:29.693088   9.258167e+06         130.000000
std                              NaN   9.820270e+05           7.528428

       Total Backward Packets  Total Length of Fwd Packets  \
count             1612.000000                  1612.000000
mean                 3.153226                   318.084988
min                  0.000000                     0.000000
25%                  0.000000                     0.000000
50%                  2.000000                     2.000000
75%                  2.000000                    86.000000
max                181.000000                 57956.000000
std                  9.191701                  1912.781450

       Total Length of Bwd Packets  Fwd Packet Length Max  \
count                  1612.000000            1612.000000
mean                   1206.041563              87.813275
min                       0.000000               0.000000
25%                       0.000000               0.000000
50%                       0.000000               1.000000
75%                     146.000000              43.000000
max                  174634.000000            2980.000000
std                    8920.726381             310.633124

       Fwd Packet Length Min  Fwd Packet Length Mean  Fwd Packet Length Std  \
count            1612.000000             1612.000000            1612.000000
mean               13.478288               32.469916              27.896802
min                 0.000000                0.000000               0.000000
25%                 0.000000                0.000000               0.000000
50%                 0.000000                1.000000               0.000000
75%                29.000000               35.000000               0.000000
max              1383.000000             1895.333333            1246.803914
std                54.757658              104.825582             107.661596

       Bwd Packet Length Max  Bwd Packet Length Min  Bwd Packet Length Mean  \
count            1612.000000            1612.000000             1612.000000
mean              201.044665              26.222705               70.426682
min                 0.000000               0.000000                0.000000
25%                 0.000000               0.000000                0.000000
50%                 0.000000               0.000000                0.000000
75%                69.000000              47.000000               63.000000
max              3452.000000             323.000000             1997.894737
std               648.556071              49.196669              186.762060

       Bwd Packet Length Std  Flow Bytes/s  Flow Packets/s  Flow IAT Mean  \
count            1612.000000  1.602000e+03    1.612000e+03   1.612000e+03
mean               56.089314           inf             inf   6.313156e+04
min                 0.000000  0.000000e+00    3.432401e-01   0.000000e+00
25%                 0.000000  0.000000e+00    1.091217e+02   4.800000e+01
50%                 0.000000  7.378979e+02    1.918327e+02   6.939333e+03
75%                 0.000000  1.243500e+04    3.596671e+04   1.085573e+04
max              1256.879653           inf             inf   5.826825e+06
std               204.433379           NaN             NaN   3.101009e+05

       Flow IAT Std  Flow IAT Max  Flow IAT Min  Fwd IAT Total  Fwd IAT Mean  \
count  1.612000e+03  1.612000e+03  1.612000e+03   1.612000e+03  1.612000e+03
mean   9.136187e+04  2.143919e+05  1.389831e+04   2.081348e+05  6.312024e+04
min    0.000000e+00  0.000000e+00  0.000000e+00   0.000000e+00  0.000000e+00
25%    2.121320e+00  9.275000e+01  1.000000e+00   1.000000e+00  1.000000e+00
50%    1.201698e+04  2.086550e+04  1.000000e+00   2.000000e+00  2.000000e+00
75%    1.871113e+04  4.292050e+04  1.000000e+00   4.500000e+01  3.462500e+01
max    4.140373e+06  9.258158e+06  5.826825e+06   9.258167e+06  5.826825e+06
std    3.923618e+05  8.449500e+05  2.241417e+05   9.150719e+05  3.494270e+05

        Fwd IAT Std   Fwd IAT Max   Fwd IAT Min  Bwd IAT Total  Bwd IAT Mean  \
count  1.612000e+03  1.612000e+03  1.612000e+03   1.612000e+03  1.612000e+03
mean   8.373860e+04  1.753890e+05  1.328931e+04   7.353358e+04  1.176803e+04
min    0.000000e+00  0.000000e+00  0.000000e+00   0.000000e+00  0.000000e+00
25%    0.000000e+00  1.000000e+00  1.000000e+00   0.000000e+00  0.000000e+00
50%    0.000000e+00  2.000000e+00  1.000000e+00   1.000000e+00  1.000000e+00
75%    1.527525e+00  4.500000e+01  2.000000e+00   3.000000e+00  2.000000e+00
max    4.157323e+06  9.258158e+06  5.826825e+06   6.300430e+06  2.467052e+06
std    4.327040e+05  8.104357e+05  2.240727e+05   4.365389e+05  9.088745e+04

        Bwd IAT Std   Bwd IAT Max  Bwd IAT Min  Fwd PSH Flags  Bwd PSH Flags  \
count  1.612000e+03  1.612000e+03  1612.000000     1612.00000         1612.0
mean   2.100899e+04  5.111834e+04     5.380273        0.14206            0.0
min    0.000000e+00  0.000000e+00     0.000000        0.00000            0.0
25%    0.000000e+00  0.000000e+00     0.000000        0.00000            0.0
50%    0.000000e+00  1.000000e+00     1.000000        0.00000            0.0
75%    0.000000e+00  2.000000e+00     2.000000        0.00000            0.0
max    3.488936e+06  4.982554e+06   249.000000        1.00000            0.0
std    1.462659e+05  3.227015e+05    16.317989        0.34922            0.0

       Fwd URG Flags  Bwd URG Flags  Fwd Header Length  Bwd Header Length  \
count         1612.0         1612.0       1.612000e+03       1.612000e+03
mean             0.0            0.0      -1.186648e+07      -1.186648e+07
min              0.0            0.0      -2.125438e+09      -2.125438e+09
25%              0.0            0.0       4.000000e+01       0.000000e+00
50%              0.0            0.0       4.000000e+01       4.000000e+01
75%              0.0            0.0       6.400000e+01       6.400000e+01
max              0.0            0.0       2.960000e+03       3.644000e+03
std              0.0            0.0       1.584186e+08       1.584186e+08

       Fwd Packets/s   Bwd Packets/s  Min Packet Length  Max Packet Length  \
count   1.612000e+03     1612.000000        1612.000000        1612.000000
mean    3.153422e+05     2212.933962          11.499380         222.980769
min     0.000000e+00        0.000000           0.000000           0.000000
25%     5.024510e+01        0.000000           0.000000           0.000000
50%     9.587728e+01       48.605631           0.000000          31.000000
75%     1.178215e+04       95.762509          29.000000          73.000000
max     3.000000e+06  1000000.000000         315.000000        3452.000000
std     6.595150e+05    38995.015976          26.026093         676.525822

       Packet Length Mean  Packet Length Std  Packet Length Variance  \
count         1612.000000        1612.000000            1.612000e+03
mean            52.227275          60.991993            3.506543e+04
min              0.000000           0.000000            0.000000e+00
25%              0.000000           0.000000            0.000000e+00
50%             11.583333           0.547723            3.000000e-01
75%             51.400000          23.868228            5.696923e+02
max           1650.434783        1255.979663            1.577485e+06
std            127.203449         177.101277            1.499474e+05

       FIN Flag Count  SYN Flag Count  RST Flag Count  PSH Flag Count  \
count          1612.0     1612.000000      1612.00000          1612.0
mean              0.0        0.003722         0.14206             0.0
min               0.0        0.000000         0.00000             0.0
25%               0.0        0.000000         0.00000             0.0
50%               0.0        0.000000         0.00000             0.0
75%               0.0        0.000000         0.00000             0.0
max               0.0        1.000000         1.00000             0.0
std               0.0        0.060914         0.34922             0.0

       ACK Flag Count  URG Flag Count  CWE Flag Count  ECE Flag Count  \
count     1612.000000     1612.000000     1612.000000          1612.0
mean         0.133995        0.527295        0.097395             0.0
min          0.000000        0.000000        0.000000             0.0
25%          0.000000        0.000000        0.000000             0.0
50%          0.000000        1.000000        0.000000             0.0
75%          0.000000        1.000000        0.000000             0.0
max          1.000000        1.000000        1.000000             0.0
std          0.340753        0.499409        0.296586             0.0

       Down/Up Ratio  Average Packet Size  Avg Fwd Segment Size  \
count    1612.000000          1612.000000           1612.000000
mean        0.679280            59.387973             32.469916
min         0.000000             0.000000              0.000000
25%         0.000000             0.000000              0.000000
50%         1.000000            13.900000              1.000000
75%         1.000000            64.250000             35.000000
max        10.000000          1725.454545           1895.333333
std         0.721742           134.964215            104.825582

       Avg Bwd Segment Size  Fwd Header Length.1  Fwd Avg Bytes/Bulk  \
count           1612.000000         1.612000e+03              1612.0
mean              70.426682        -1.186648e+07                 0.0
min                0.000000        -2.125438e+09                 0.0
25%                0.000000         4.000000e+01                 0.0
50%                0.000000         4.000000e+01                 0.0
75%               63.000000         6.400000e+01                 0.0
max             1997.894737         2.960000e+03                 0.0
std              186.762060         1.584186e+08                 0.0

       Fwd Avg Packets/Bulk  Fwd Avg Bulk Rate  Bwd Avg Bytes/Bulk  \
count                1612.0             1612.0              1612.0
mean                    0.0                0.0                 0.0
min                     0.0                0.0                 0.0
25%                     0.0                0.0                 0.0
50%                     0.0                0.0                 0.0
75%                     0.0                0.0                 0.0
max                     0.0                0.0                 0.0
std                     0.0                0.0                 0.0

       Bwd Avg Packets/Bulk  Bwd Avg Bulk Rate  Subflow Fwd Packets  \
count                1612.0             1612.0          1612.000000
mean                    0.0                0.0             3.913772
min                     0.0                0.0             1.000000
25%                     0.0                0.0             2.000000
50%                     0.0                0.0             2.000000
75%                     0.0                0.0             3.000000
max                     0.0                0.0           130.000000
std                     0.0                0.0             7.528428

       Subflow Fwd Bytes  Subflow Bwd Packets  Subflow Bwd Bytes  \
count        1612.000000          1612.000000        1612.000000
mean          318.084988             3.153226        1206.041563
min             0.000000             0.000000           0.000000
25%             0.000000             0.000000           0.000000
50%             2.000000             2.000000           0.000000
75%            86.000000             2.000000         146.000000
max         57956.000000           181.000000      174634.000000
std          1912.781450             9.191701        8920.726381

       Init_Win_bytes_forward  Init_Win_bytes_backward  act_data_pkt_fwd  \
count             1612.000000              1612.000000       1612.000000
mean              7972.224566              2221.971464          1.362283
min                 -1.000000                -1.000000          0.000000
25%                 -1.000000                -1.000000          0.000000
50%                254.000000                -1.000000          1.000000
75%              16228.000000               256.000000          1.000000
max              65535.000000             63919.000000         96.000000
std              14597.432594              8357.310024          3.874860

       min_seg_size_forward   Active Mean  Active Std    Active Max  \
count          1.612000e+03   1612.000000      1612.0   1612.000000
mean          -5.933262e+06     12.701613         0.0     12.701613
min           -1.062719e+09      0.000000         0.0      0.000000
25%            2.000000e+01      0.000000         0.0      0.000000
50%            2.000000e+01      0.000000         0.0      0.000000
75%            2.000000e+01      0.000000         0.0      0.000000
max            1.480000e+03  20468.000000         0.0  20468.000000
std            7.920930e+07    509.791760         0.0    509.791760

         Active Min     Idle Mean  Idle Std      Idle Max      Idle Min  \
count   1612.000000  1.612000e+03    1612.0  1.612000e+03  1.612000e+03
mean      12.701613  2.002494e+04       0.0  2.002494e+04  2.002494e+04
min        0.000000  0.000000e+00       0.0  0.000000e+00  0.000000e+00
25%        0.000000  0.000000e+00       0.0  0.000000e+00  0.000000e+00
50%        0.000000  0.000000e+00       0.0  0.000000e+00  0.000000e+00
75%        0.000000  0.000000e+00       0.0  0.000000e+00  0.000000e+00
max    20468.000000  9.258158e+06       0.0  9.258158e+06  9.258158e+06
std      509.791760  3.678824e+05       0.0  3.678824e+05  3.678824e+05

           Inbound
count  1612.000000
mean      0.140819
min       0.000000
25%       0.000000
50%       0.000000
75%       0.000000
max       1.000000
std       0.347943
         Unnamed: 0   Source Port  Destination Port      Protocol  \
count  2.179930e+06  2.179930e+06      2.179930e+06  2.179930e+06
mean   1.704530e+04  8.208814e+02      3.278819e+04  1.699764e+01
min    0.000000e+00  0.000000e+00      0.000000e+00  0.000000e+00
25%    8.525000e+03  6.610000e+02      1.643100e+04  1.700000e+01
50%    1.704500e+04  8.110000e+02      3.279000e+04  1.700000e+01
75%    2.556500e+04  9.000000e+02      4.916500e+04  1.700000e+01
max    3.420300e+04  6.541300e+04      6.553500e+04  1.700000e+01
std    9.838061e+03  1.399167e+03      1.891124e+04  1.701792e-01

                           Timestamp  Flow Duration  Total Fwd Packets  \
count                        2179930   2.179930e+06       2.179930e+06
mean   2018-12-01 11:27:31.223158016   4.753094e+02       4.525275e+00
min       2018-12-01 11:22:40.254769   0.000000e+00       1.000000e+00
25%    2018-12-01 11:25:04.192280320   1.000000e+00       2.000000e+00
50%    2018-12-01 11:27:27.115724032   1.000000e+00       2.000000e+00
75%    2018-12-01 11:29:58.081458432   2.000000e+00       2.000000e+00
max       2018-12-01 11:32:32.915361   1.116618e+07       8.622100e+04
std                              NaN   5.828400e+04       4.649890e+02

       Total Backward Packets  Total Length of Fwd Packets  \
count            2.179930e+06                 2.179930e+06
mean             9.991147e-04                 2.935451e+03
min              0.000000e+00                 0.000000e+00
25%              0.000000e+00                 2.944000e+03
50%              0.000000e+00                 2.944000e+03
75%              0.000000e+00                 2.944000e+03
max              9.400000e+01                 5.888000e+04
std              1.297934e-01                 2.901330e+02

       Total Length of Bwd Packets  Fwd Packet Length Max  \
count                 2.179930e+06           2.179930e+06
mean                  6.643975e-02           1.463728e+03
min                   0.000000e+00           0.000000e+00
25%                   0.000000e+00           1.472000e+03
50%                   0.000000e+00           1.472000e+03
75%                   0.000000e+00           1.472000e+03
max                   4.378000e+03           1.472000e+03
std                   1.530665e+01           5.126138e+01

       Fwd Packet Length Min  Fwd Packet Length Mean  Fwd Packet Length Std  \
count           2.179930e+06            2.179930e+06           2.179930e+06
mean            1.463717e+03            1.463720e+03           4.671605e-03
min             0.000000e+00            0.000000e+00           0.000000e+00
25%             1.472000e+03            1.472000e+03           0.000000e+00
50%             1.472000e+03            1.472000e+03           0.000000e+00
75%             1.472000e+03            1.472000e+03           0.000000e+00
max             1.472000e+03            1.472000e+03           3.446781e+02
std             5.151614e+01            5.143812e+01           1.017299e+00

       Bwd Packet Length Max  Bwd Packet Length Min  Bwd Packet Length Mean  \
count           2.179930e+06           2.179930e+06            2.179930e+06
mean            2.107086e-02           4.917589e-04            7.890693e-03
min             0.000000e+00           0.000000e+00            0.000000e+00
25%             0.000000e+00           0.000000e+00            0.000000e+00
50%             0.000000e+00           0.000000e+00            0.000000e+00
75%             0.000000e+00           0.000000e+00            0.000000e+00
max             1.073000e+03           1.072000e+03            1.072000e+03
std             4.662010e+00           7.260617e-01            1.923845e+00

       Bwd Packet Length Std  Flow Bytes/s  Flow Packets/s  Flow IAT Mean  \
count           2.179930e+06  2.179928e+06    2.179930e+06   2.179930e+06
mean            9.817320e-03           inf             inf   3.650872e+01
min             0.000000e+00  0.000000e+00    5.235904e-01   0.000000e+00
25%             0.000000e+00  1.472000e+09    1.000000e+06   1.000000e+00
50%             0.000000e+00  2.944000e+09    2.000000e+06   1.000000e+00
75%             0.000000e+00  2.944000e+09    2.000000e+06   2.000000e+00
max             6.189195e+02           inf             inf   2.546520e+06
std             2.247847e+00           NaN             NaN   5.633590e+03

       Flow IAT Std  Flow IAT Max  Flow IAT Min  Fwd IAT Total  Fwd IAT Mean  \
count  2.179930e+06  2.179930e+06  2.179930e+06   2.179930e+06  2.179930e+06
mean   6.192795e+01  1.602637e+02  5.856160e+00   4.429864e+02  3.994784e+01
min    0.000000e+00  0.000000e+00  0.000000e+00   0.000000e+00  0.000000e+00
25%    0.000000e+00  1.000000e+00  1.000000e+00   1.000000e+00  1.000000e+00
50%    0.000000e+00  1.000000e+00  1.000000e+00   1.000000e+00  1.000000e+00
75%    0.000000e+00  2.000000e+00  2.000000e+00   2.000000e+00  2.000000e+00
max    4.410699e+06  7.639557e+06  2.186000e+03   1.116618e+07  2.546520e+06
std    1.043140e+04  2.352765e+04  1.867691e+01   5.661389e+04  5.897977e+03

        Fwd IAT Std   Fwd IAT Max   Fwd IAT Min  Bwd IAT Total  Bwd IAT Mean  \
count  2.179930e+06  2.179930e+06  2.179930e+06   2.179930e+06  2.179930e+06